export const SAVE_TOKEN="SAVE_TOKEN"
export const DELETE_TOKEN="DELETE_TOKEN"
export const USE_TOKEN="USE_TOKEN"
export const SKIP_TOKEN="SKIP_TOKEN"

export const API_ERROR="API_ERROR"

export const LIST_CATEGORIES="LIST_CATEGORIES"
export const TOGGLE_FEEDS="TOGGLE_FEEDS"

export const LIST_FEEDS="LIST_FEEDS"