export const SAVE_TOKEN="SAVE_TOKEN"
export const DELETE_TOKEN="DELETE_TOKEN"
export const USE_TOKEN="USE_TOKEN"
export const SKIP_TOKEN="SKIP_TOKEN"

export const API_ERROR="API_ERROR"
export const ADD_ALERT="ADD_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"

export const LIST_CATEGORIES_LOADING="LIST_CATEGORIES_LOADING"
export const LIST_CATEGORIES_FINISHED="LIST_CATEGORIES_FINISHED"
export const LIST_CATEGORIES_FAILED="LIST_CATEGORIES_FAILED"
export const LOAD_CATEGORIES_SUCCESS="LOAD_CATEGORIES_SUCCESS"

export const TOGGLE_FEEDS="TOGGLE_FEEDS"


export const LIST_FEEDS_LOADING="LIST_FEEDS_LOADING"
export const LIST_FEEDS_FINISHED="LIST_FEEDS_FINISHED"
export const LIST_FEEDS_FAILED="LIST_FEEDS_FAILED"

export const LIST_FEEDS="LIST_FEEDS"

export const FEEDLY_REQUEST_FAILED="FEEDLY_REQUEST_FAILED"
export const FEEDLY_REQUEST_LOADING="FEEDLY_REQUEST_LOADING"
export const FEEDLY_REQUEST_FINISHED="FEEDLY_REQUEST_FINISHED"

export const TOGGLE_CATEGORY_VISIBILITY="TOGGLE_CATEGORY_VISIBILITY"

export const SELECTED_STREAM_FINISHED="SELECTED_STREAM_FINISHED"
export const SELECTED_STREAM_LOADING="SELECTED_STREAM_LOADING"

export const SELECT_ITEM="SELECT_ITEM"
export const CLEAR_SELECTED_ITEM="CLEAR_SELECTED_ITEM"
export const SELECTED_ITEM_LOADING="SELECTED_ITEM_LOADING"
export const SUBSCRIBING_TO_FEED="SUBSCRIBING_TO_FEED"
export const SUBSCRIBING_TO_FEED_FAILED="SUBSCRIBING_TO_FEED_FAILED"
export const SUBSCRIBING_TO_FEED_FINISHED="SUBSCRIBING_TO_FEED_FINISHED"
export const LOAD_FEEDS_SUCCESS="LOAD_FEEDS_SUCCESS"